---

template_path: glawit/dns.yaml

stack_tags:
   Purpose: backup
   repository: music

parameters:
   ApiId: !stack_output apis/music/api.yaml::ApiId
   CertificateArn: !stack_output apis/music/certificate.yaml::CertificateArn
   DomainName: music.{{ base_domain }}
   HostedZoneId: {{ hosted_zone_id }}
   StageName: !stack_output apis/music/stages/stable.yaml::Name
