---

#hooks:
#   before_launch:
#      - !cmd >
#         sh
#         --
#         package.sh
#         {{ lambda_deployment_bucket }}
#         3.7
#         3.8

template_path: glawit/layer.yaml

stack_tags:
   Purpose: git-lfs

parameters:
   DeploymentBucket: {{ lambda_deployment_bucket }}
   DeploymentObjectKey: !file_contents .glawit_deployment_package/object_key
   PythonVersions:
      - python3.7
