---

template_path: glawit/route.yaml

stack_tags:
   Purpose: git-lfs
   repository: music

parameters:
   ApiId: !stack_output apis/music/api.yaml::ApiId
   HttpMethod: POST
   LambdaArn: !stack_output apis/music/lambda/functions/verify/post.yaml::FunctionArn
   RouteKey: /verify
