---

template_path: glawit/function.yaml

stack_tags:
   Purpose: git-lfs
   repository: git-lfs-playground

parameters:
   GitHubOwner: {{ github_owner }}
   GitHubRepo: {{ github_repo }}
   HandlerFunction: post
   HandlerModule: locks.verify
   Policies:
      - !stack_output apis/playground/locktable.yaml::LockManagementPolicyArn
   PythonVersion: '{{ python_version }}'
