---


AWSTemplateFormatVersion: 2010-09-09


Description: 'git LFS: Bucket'


Resources:

   Bucket:
      Type: AWS::S3::Bucket
      Properties:
         PublicAccessBlockConfiguration:
            BlockPublicAcls: true
            BlockPublicPolicy: true
            IgnorePublicAcls: true
            RestrictPublicBuckets: true


Outputs:

   BucketName:
      Description: Name of the S3 bucket.
      Value:
         Ref: Bucket
