---


AWSTemplateFormatVersion: 2010-09-09


Description: 'git LFS: Handler'


Metadata:

   AWS::CloudFormation::Interface:
      ParameterLabels:
         ApiId:
            default: API Gateway API ID
         DeploymentBucket:
            default: Bucket
         DeploymentObjectKey:
            default: Object key
         DeploymentObjectVersion:
            default: Object version ID
         GitLfsBucketName:
            default: Bucket

      ParameterGroups:
         -
            Label: Deployment
            Parameters:
               - DeploymentBucket
               - DeploymentObjectKey
               - DeploymentObjectVersion
         -
            Label: Git LFS
            Parameters:
               - ApiId
               - GitLfsBucketName


Parameters:

   ApiId:
      Description: API Gateway API ID.
      Type: String

   DeploymentBucket:
      Description: Name of the S3 bucket containing the deployment package.
      Type: String

   DeploymentObjectKey:
      Description: Object key for the deployment package.
      Type: String

   DeploymentObjectVersion:
      Description: Version ID of deployment package.
      Type: String

   GitLfsBucketName:
      Description: Name of the S3 bucket.
      Type: String


Resources:

   Role:
      Type: AWS::IAM::Role
      Properties:
         AssumeRolePolicyDocument:
            Version: 2012-10-17
            Statement:
               -
                  Principal:
                     Service: lambda.amazonaws.com
                  Action:
                     - sts:AssumeRole
                  Effect: Allow
         ManagedPolicyArns:
            -
               Fn::Sub: arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
         Policies:
            -
               PolicyName: bucket
               PolicyDocument:
                  Version: 2012-10-17
                  Statement:
                     -
                        Sid: Bucket
                        Action:
                           - s3:ListBucket
                        Resource:
                           -
                              Fn::Sub: arn:${AWS::Partition}:s3:::${GitLfsBucketName}
                        Effect: Allow
                     -
                        Sid: Objects
                        Action:
                           - s3:GetObject
                           - s3:GetObjectTagging
                           - s3:PutObject
                           - s3:PutObjectTagging
                        Resource:
                           -
                              Fn::Sub: arn:${AWS::Partition}:s3:::${GitLfsBucketName}/*
                        Effect: Allow

   Function:
      Type: AWS::Lambda::Function
      Properties:
         Code:
            # FIXME: support S3ObjectVersion
            S3Bucket:
               Ref: DeploymentBucket
            S3Key:
               Ref: DeploymentObjectKey
         Description: git LFS API handler
         Environment:
            Variables:
               AWS_PARTITION:
                  Ref: AWS::Partition
               Bucket:
                  Ref: GitLfsBucketName
         Handler: lambda.handler
         MemorySize: 128
         Role:
            Fn::GetAtt:
               - Role
               - Arn
         # FIXME
         #Runtime: python3.8
         Runtime: python3.7
         Timeout: 5

   Permission:
      Type: AWS::Lambda::Permission
      Properties:
         Principal: apigateway.amazonaws.com
         # FIXME
         #SourceArn:
         #   Fn::Sub: arn:${AWS::Partition}:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiId}/
         Action: lambda:InvokeFunction
         FunctionName:
            Ref: Function


Outputs:

   FunctionName:
      Description: Name of the Lambda function.
      Value:
         Ref: Function
