---

template_path: glawit/route.yaml

stack_tags:
   Purpose: backup
   repository: music

parameters:
   ApiId: !stack_output apis/music/api.yaml::ApiId
   HttpMethod: POST
   LambdaArn: !stack_output apis/music/lambda/functions/locks/id/unlock/post.yaml::FunctionArn
   RouteKey: /locks/{lock_id}/unlock
