---

template_path: glawit/function.yaml

stack_tags:
   Purpose: git-lfs
   repository: git-lfs-playground

parameters:
   GitHubOwner: {{ github_owner }}
   GitHubRepo: {{ github_repo }}
   HandlerFunction: post
   HandlerModule: locks.id.unlock
   LargeFileStorageClass: STANDARD
   LargeFileStoreBucketName: !stack_output apis/playground/store.yaml::BucketName
   Layers:
      - !stack_output lambda/layers/glawit.yaml::LatestVersionArn
   LockTable: !stack_output apis/playground/locktable.yaml::TableName
   Policies:
      - !stack_output apis/playground/locktable.yaml::LockDeletionPolicyArn
   PythonVersion: '{{ python_version }}'
