---

template_path: glawit/certificate.yaml

stack_tags:
   Purpose: git-lfs
   repository: git-lfs-playground

parameters:
   DomainName: playground.{{ base_domain }}
   HostedZoneId: {{ hosted_zone_id }}
