---

template_path: glawit/dns.yaml

stack_tags:
   Purpose: git-lfs
   repository: git-lfs-playground

parameters:
   ApiId: !stack_output apis/playground/api.yaml::ApiId
   CertificateArn: !stack_output apis/playground/certificate.yaml::CertificateArn
   DomainName: playground.{{ base_domain }}
   HostedZoneId: {{ hosted_zone_id }}
   StageName: !stack_output apis/playground/stages/staging.yaml::Name
