---

template_path: glawit/function.yaml

stack_tags:
   Purpose: git-lfs
   repository: music

parameters:
   ApiId: !stack_output apis/music/api.yaml::ApiId
   DeploymentBucket: {{ lambda_deployment_bucket }}
   DeploymentObjectKey: !file_contents lambda/functions/objects/batch/deployment-object-key
   DeploymentObjectVersion: ''
   GitLfsBucketName: !stack_output apis/music/bucket.yaml::BucketName
   GitLfsStorageClass: STANDARD
   HttpMethod: POST
   HttpPath: /objects/batch

hooks:
   before_launch:
      - !cmd sh -- deploy.sh {{ lambda_deployment_bucket }} lambda/functions/objects/batch
