---

template_path: glawit/route.yaml

stack_tags:
   Purpose: git-lfs
   repository: git-lfs-playground

parameters:
   ApiId: !stack_output apis/playground/api.yaml::ApiId
   HttpMethod: POST
   LambdaArn: !stack_output apis/playground/lambda/functions/locks/post.yaml::FunctionArn
   RouteKey: /locks
